### ISSUE TITLE
No train_bio.py

### ISSUE THREAD

**Issue by yangjingla** [zjunlp/DocuNet#13]
Both in  CDR and GDA  running bash 

```
#! /bin/bash
export CUDA_VISIBLE_DEVICES=0

if true; then
type=context-based
bs=4
bl=3e-5
uls=(4e-4)
accum=1
for ul in ${uls[@]}
do
python -u  ./train_bio.py --data_dir ./dataset/cdr \
  --max_height 35 \
  --channel_type $type \
  --bert_lr $bl \
  --transformer_type bert \
  --model_name_or_path allenai/scibert_scivocab_cased \
  --train_file train.data \
  --dev_file dev.data \
  --test_file test.data \
  --train_batch_size $bs \
  --test_batch_size $bs \
  --gradient_accumulation_steps $accum \
  --num_labels 1 \
  --learning_rate $ul \
  --max_grad_norm 1.0 \
  --warmup_ratio 0.06 \
  --num_train_epochs 30 \
  --seed 111 \
  --num_class 2 \
  --save_path ./checkpoint/cdr/train_scibert-lr${bl}_accum${accum}_unet-lr${ul}_bs${bs}.pt \
  --log_dir ./logs/cdr/train_scibert-lr${bl}_accum${accum}_unet-lr${ul}_bs${bs}.log
done
fi
```

**Comment by yangjingla** [comment]
And this code is obviously modified based on ATLOP(https://github.com/wzhouad/ATLOP), I think it is better to state this in the README😄

**Comment by zxlzr** [comment]
We have revised the README and stated this, many thanks.

**Comment by ady-yu** [comment]
> We have revised the README and stated this, many thanks.
when I run the cdr dataset .
` ret = torch.addmm(bias, input, weight.t())
RuntimeError: mat1 dim 1 must match mat2 dim 0`

**Comment by TimelordRi** [comment]
@ady-yu I just clone and re-run the code but no error appears. Could you offer a full error traceback message or check the changes you make to the code?

**Comment by ady-yu** [comment]
> @ady-yu I just clone and re-run the code but no error appears. Could you offer a full error traceback message or check the changes you make to the code?

sorry,I met this problem.
![image](https://user-images.githubusercontent.com/69707855/147541221-174e6bd2-fce6-43ed-8d30-20bf8edd40a4.png)
It seems in your updated train_bio.py, you use the following code to read the cdr data. 
![image](https://user-images.githubusercontent.com/69707855/147541294-a3a64468-0f4d-41bb-9f49-18e5361cdc0f.png)
But in prepro.py ,the read_cdr function is following
![image](https://user-images.githubusercontent.com/69707855/147541365-fde2838e-3263-4d04-8666-9ed311297bca.png)

**Comment by TimelordRi** [comment]
@ady-yu Hey there! I find this bug when I re-run the code and fix it rightnow. You could see the update to solve this error. Thx! : )

**Comment by ady-yu** [comment]
> @ady-yu Hey there! I find this bug when I re-run the code and fix it rightnow. You could see the update to solve this error. Thx! : )

Thanks a lot!!!

**Comment by ady-yu** [comment]
> @ady-yu Hey there! I find this bug when I re-run the code and fix it rightnow. You could see the update to solve this error. Thx! : )

![image](https://user-images.githubusercontent.com/69707855/147543750-6dd18c18-51b5-453a-aa08-179c01c74d09.png)
Is there something wrong? when I run the cdr dataset , the f1 score is so high!
