### ISSUE TITLE
ERROR: No matching distribution found for transformers==3.0.4  

### ISSUE THREAD

**Issue by Torres9999** [zjunlp/DocuNet#14]
想问下 这个 transformers==3.0.4 到底是哪个版本 。 我用4.17和3.4.0，都尝试了 ，还是会报各种库里面的错

**Comment by Torres9999** [comment]
pip install transformers==3.0.4
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
ERROR: Could not find a version that satisfies the requirement transformers==3.0.4 (from versions: 0.1, 2.0.0, 2.1.0, 2.1.1, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.4.0, 2.4.1, 2.5.0, 2.5.1, 2.6.0, 2.7.0, 2.8.0, 2.9.0, 2.9.1, 2.10.0, 2.11.0, 3.0.0, 3.0.1, 3.0.2, 3.1.0, 3.2.0, 3.3.0, 3.3.1, 3.4.0, 3.5.0, 3.5.1, 4.0.0rc1, 4.0.0, 4.0.1, 4.1.0, 4.1.1, 4.2.0, 4.2.1, 4.2.2, 4.3.0rc1, 4.3.0, 4.3.1, 4.3.2, 4.3.3, 4.4.0, 4.4.1, 4.4.2, 4.5.0, 4.5.1, 4.6.0, 4.6.1, 4.7.0, 4.8.0, 4.8.1, 4.8.2, 4.9.0, 4.9.1, 4.9.2, 4.10.0, 4.10.1, 4.10.2, 4.10.3, 4.11.0, 4.11.1, 4.11.2, 4.11.3, 4.12.0, 4.12.1, 4.12.2, 4.12.3, 4.12.4, 4.12.5, 4.13.0, 4.14.0, 4.14.1, 4.15.0, 4.16.0, 4.16.1, 4.16.2, 4.17.0)
ERROR: No matching distribution found for transformers==3.0.4

**Comment by Torres9999** [comment]
TypeError: ElementWiseMatrixAttention.forward: `matrix_1` is not present.

**Comment by LawsonAbs** [comment]
> 
我也遇到了这个问题，这个应该是allennlp版本不对导致的。装1.0.0版本就好了。

**Comment by LawsonAbs** [comment]
> TypeError: ElementWiseMatrixAttention.forward: `matrix_1` is not present.
抱歉，当我尝试降低allennlp版本的时候，如果安装torch 1.5.0 的话，我的模型加载到显卡是非常缓慢的（几乎加载不进去），后来我升级了torch 的版本到1.7.0  ，transformer 到 4.2.2  ,allennlp 2.0.0

**Comment by LawsonAbs** [comment]
同时：我的CUDA Version: 11.4
