### ISSUE TITLE
对预测矩阵的疑问

### ISSUE THREAD

**Issue by LawsonAbs** [zjunlp/DocuNet#16]
![image](https://user-images.githubusercontent.com/35190068/163182307-6f04a8f9-7aa5-4dfd-a9a3-ae42911721a5.png)
如上所示，是论文中Figure 5的右半部分，请问 DocUnet 这种方法最后是预测实体对间的关系是只能有一种吗？

**Comment by njcx-ai** [comment]
您好，感谢您的关注。DocUnet 这种方法最后预测实体对间的关系可以不止是一种，论文涉及的数据集中DocRED数据集属于多标签分类。

**Comment by LawsonAbs** [comment]
假设有两个三元组(e1,r1,e2) (e1,r2,e2)，r1的id为1，r2的id为2，那是怎么在上面这个矩阵中体现的呢？

**Comment by njcx-ai** [comment]
您好，这个矩阵图只是示意实体级关系矩阵对应的label， 假设有两个三元组(e1,r1,e2) (e1,r2,e2)，就同时保留（r1, r2)。
具体代码实现时对应的是第三维的向量表示关系预测。
