### ISSUE TITLE
下载代码

### ISSUE THREAD

**Issue by zhangxq9944** [zjunlp/DocuNet#2]
您好，想问问一下，代码哪里可以下载呢？
还有以下几个问题想请教一下：
1、做文档级关系抽取，句子中会用到指代词，比如 they,it,he,this 等等，这些指代词需要做替换吗？还是将指带关系-coreference,也放入到文档级关系的识别过程中?
2、做文档级关系抽取， define a N × N matrix Y，这个矩阵Y 的   行是训练集中所有的实体吗，还是每一篇文档构建一个矩阵Y？
3、在实验设置中，提到了“We set the matrix size N = 42” 这个矩阵是指的第二条的矩阵Y吗？
这个42指的是什么呢？怎样获得的呢？

**Comment by zxlzr** [comment]
您好，
1. 我们实验的数据集中只抽取给定实体间的关系，这部分不需要做替换，但真实场景做好指代会提升效果。
2. 每一篇文章构建一个矩阵Y，这里N=42是最大实体个数，部分文档实体个数小于42。
3. 代码将于近期放出。

**Comment by zhangxq9944** [comment]
非常感谢
