### ISSUE TITLE
More recent trained DocRED Weights?

### ISSUE THREAD

**Issue by joseMalaquias** [zjunlp/DocuNet#22]
Hello!

Thank you for the awesome repository.

Is it possible to share an updated version of the trained weights for DocRED or the result.json file? The trained weights shared on issue #9 don't predict anything on the official evaluation. 

I am doing a research thesis and not having to train the model would save me a lot of time. I'm performing this task on a model I developed but my model can only predict positive labels (non-Na) and the result.json file generated by this model would help me filter the Na examples. My ideia would be for my model to predict the pairs of labels your model predicted. As I don't have access to enough GPU memory I am not able to train your model from scratch. 

Thank you very much.

**Comment by zxlzr** [comment]
Did you use the correct data or evaluation scripts? We are recently running out of resources to re-train a model (No budget), which may take some time.

**Comment by joseMalaquias** [comment]
Yes, I used the right script (official evaluation) and submitted the result.json into the Codalab DocRED competition. If you don't have an already fine-tuned model don't worry. Thank you, nevertheless.

**Comment by zxlzr** [comment]
We will try to release a fine-tuned checkpoint when having enough GPU resources.

**Comment by joseMalaquias** [comment]
Thank you very much.
