### ISSUE TITLE
您好，请问随机种子固定后，复现后每次结果都不相同是什么原因？怎么才能在随机种子相同时固定复现结果？

### ISSUE THREAD

**Issue by hujy025** [zjunlp/DocuNet#23]

**Comment by njcx-ai** [comment]
您好，很抱歉代码中随机种子固定的策略可能有遗漏。
如果种子设置没问题的话，结果还是不一样可能是torch.backends.cudnn.benchmark的问题。这是python调用cudnn来加速卷积的一个机制。解决方法是将torch.backends.cudnn.benchmark = False，然后直接加一句torch.backends.cudnn.deterministic = True。

**Comment by noBugYY** [comment]
亲爱的小伙伴辛苦了，您发送的邮件我已经收到，谢谢！

**Comment by yxy0102** [comment]
作者你好，我也遇到了这个问题，并且我在set_seed里加入了您说的那两行代码，但是每次的结果还是在变化，还有什么解决办法吗
![0be97e2d9d2742328ca6456771a6854](https://user-images.githubusercontent.com/77889563/222959037-40463aed-4caa-43fe-86b1-dcae20f2dbbe.png)

**Comment by zxlzr** [comment]
您好，我建议您检查下是否还有部分参数的种子没有fix，我也不是很清楚您这种情况非常抱歉。

**Comment by noBugYY** [comment]
亲爱的小伙伴辛苦了，您发送的邮件我已经收到，谢谢！
