### ISSUE TITLE
数据集咋下载

### ISSUE THREAD

**Issue by ARDUJS** [zjunlp/DocuNet#24]
您好，想请教下，我应该去哪下载数据集，并且对于数据集应该进行哪些操作？
我运行命令：bash scripts/run_cdr.sh
FileNotFoundError: [Errno 2] No such file or directory: './dataset/cdr/train_filter.data'

**Comment by zxlzr** [comment]
您好，可以从这里下载cdr https://github.com/fenchri/edge-oriented-graph
