### ISSUE TITLE
结果不一致

### ISSUE THREAD

**Issue by ARDUJS** [zjunlp/DocuNet#25]
hello，为什么我跑cdr数据集，出来的f1值是85左右，然后论文给出的是76.3

**Comment by zxlzr** [comment]
恭喜您取得了更好的结果。目前给的超参数是经过优化的，在不同GPU、不同batchsize大小和更长训练步数下会有更好的结果出现。您可以参见https://github.com/zjunlp/DocuNet/issues/18

**Comment by ARDUJS** [comment]
> 

thank you

**Comment by MrDreamQ** [comment]
> hello，为什么我跑cdr数据集，出来的f1值是85左右，然后论文给出的是76.3
你好，请问你是调整过什么参数才得到这个结果的？

**Comment by RittoQin** [comment]
> hello，为什么我跑cdr数据集，出来的f1值是85左右，然后论文给出的是76.3

你好，你是调整什么参数才跑到这个结果的？
