### ISSUE TITLE
关于分割区域的一点疑问

### ISSUE THREAD

**Issue by nlper01** [zjunlp/DocuNet#29]
![image](https://github.com/zjunlp/DocuNet/assets/82627285/78d63a8e-a688-4721-965b-05bfc0f1f842)
As it shows in the Figure 2, the segmentation area in the entitylevel relation matrix refers to the co-occurrence of relations between entity pairs.

首先图二中的红框是想表示什么意思？分割区域是连续的，论文中说分割区域是指实体级关系矩阵中关系的共现，也就是指图2中的一个格子（像素点）？

**Comment by zxlzr** [comment]
您好，这个实体矩阵图是在类比图片，并非和图片一样是连续的，一个块类比对应一个像素点，通过卷积建模不同点之间的关联。框是示意图（仅为便于理解）表达模型需要建模框内的像素点的关联。

**Comment by nlper01** [comment]
> 您好，这个实体矩阵图是在类比图片，并非和图片一样是连续的，一个块类比对应一个像素点，通过卷积建模不同点之间的关联。框是示意图（仅为便于理解）表达模型需要建模框内的像素点的关联。

大佬，这个我理解。
1、我是想问对于这个任务分割区域指的是什么？论文中说分割区域是指实体级关系矩阵中关系的共现，这个怎么理解，没太明白。
2、另外，还想问一下主模型图中的 Unet模块部分中的  FFD  是指什么？
