### ISSUE TITLE
关于损失函数的一些疑问

### ISSUE THREAD

**Issue by 180808118** [zjunlp/DocuNet#30]
![image](https://github.com/zjunlp/DocuNet/assets/67565706/aac6f340-2a5a-4489-8771-bd0fd0ff767c)
看到模型里面self.loss_fnt=ATLoss()
但是这个实际上在上面引入时是balanced_loss，想问一下这里是试过之后发现相较于ATLoss，交叉熵在某些方面更好一些是吗

**Comment by njcx-ai** [comment]
您好，非常感谢您对我们之前工作的关注。项目里实际使用的是balanced_loss会相对ATLoss好一些。

**Comment by zxlzr** [comment]
请问您是否还有其他问题？

**Comment by 180808118** [comment]
没有了，非常感谢回复
