### ISSUE TITLE
理解模型图框架中一些疑惑

### ISSUE THREAD

**Issue by huruqi10** [zjunlp/DocuNet#33]
请问U-shaped Segmentation Module框架图中的FFD是代表的什么啊？看代码中就是一个卷积层.

**Comment by njcx-ai** [comment]
您好，非常感谢您对本文的关注。FFD代表的是基于FFN的decoder，具体是将矩阵映射到分类空间。

**Comment by zxlzr** [comment]
请问您还有其他问题吗?

**Comment by huruqi10** [comment]
没有了 谢谢
