### ISSUE TITLE
Question about Entity Ordering Impact on CDR Dataset Performance

### ISSUE THREAD

**Issue by ptlai** [zjunlp/DocuNet#34]
Thank you for sharing your code. It has been very helpful in developing our models.
I've been able to reproduce a performance of ~85% F1 using your code directly. However, I have a question regarding running on the CDR dataset.

Issue:
It appears that the order of ground truth relations generated by the edge-oriented-graph repository (https://github.com/fenchri/edge-oriented-graph) affects the performance. Specifically, it places all CID pairs at the beginning.

Observation:
While I understand that DocuNet doesn't utilize the truth relations, the entity_pos list loads entities based on their order in the edge-oriented-graph's preprocessed TSV file. 
https://github.com/zjunlp/DocuNet/blob/aa946e18d08107bee46fc637c0894da054932978/prepro.py#L275
If this entity order is used in generating Figure 4 of the DocuNet paper, the entities (with CID) may fall into a specific region.

Impact:
When I reordered the ground truth relations from the edge-oriented-graph, I observed a drop in performance.

Question:
Do you have any suggestions on how to address this issue or mitigate the impact of entity ordering?

Once again, thank you for open-sourcing your work. It is really helpful in our research!

**Comment by njcx-ai** [comment]
Thank you very much for your interest in our work. We apologize that our previous work did not focus on the impact of entity ordering and simply followed the original order in the data. We suggest that you could delve deeper into analyzing the underlying mechanisms of how entity ordering impacts the results.

**Comment by ptlai** [comment]
Hi @njcx-ai ,

Thanks for your prompt reply. 
Once again, thank you very much for making it available!
