### ISSUE TITLE
Question about the size of the feature map

### ISSUE THREAD

**Issue by ridiculouz** [zjunlp/DocuNet#7]
Hi,
I notice that in your paper it is said that "... N is the largest number of entities, counted from all the dataset samples". However, it seems like that in your DocRED experiment the size N is fixed to args.max_height 42. So I wonder what does N stand for?

**Comment by zxlzr** [comment]
N is the largest number of entities in datasets, for example, 42 for DocRE. Feel free to use different N for different datasets.
