### ISSUE TITLE
Trained DocRED Weights?

### ISSUE THREAD

**Issue by logan-markewich** [zjunlp/DocuNet#9]
Hello!

Thank you for the awesome work, I enjoyed reading your about and your approach.

Is it possible to share the trained weights for DocRED?

To be honest, it will save me a ton of time haha. I'm writing a paper and would like to use the trained DocRED model on a few examples. Replicating this work is proving difficult when I don't have access to enough GPU memory.

**Comment by TimelordRi** [comment]
I upload the trained model trained with the roberta-base to Google Drive now, you can find it at https://drive.google.com/drive/folders/1Ol8E3sdkQA2APh1KWhrZzEDnXXBAGQtB?usp=sharing. 

Hope this trained model can help you!

**Comment by logan-markewich** [comment]
Awesome, thank-you!

**Comment by aadiby** [comment]
@logan-markewich 
Have you had any luck using this pretrained model? I have tried running the tests using the pretrained model + roberta_base tokenizer, but i don't get any predictions out of it.

**Comment by logan-markewich** [comment]
@aadiby I just got around to finally trying it. Using the checkpoint and their scripts, I only got 0.12 F1 lol

Maybe I missed something. I used the run_docred.sh script with --load_path, using roberta-base

**Comment by logan-markewich** [comment]
I was able to retrain roberata-large though, and got 0.62 F1. Not quite the results from their paper, but close enough for me
